"""Replace em-dashes with hyphens across the project.

Scope:
  - html/*.html (excluding html/_archive/)
  - html/*.md
  - erd/*.md (the .html siblings are regenerated by build_md_pages.py)
  - CLAUDE.md and other root-level *.md
  - data/qa_data/*.md
  - parcel_development_history_etl/**/*.py (just GENEALOGY.md and similar; py files
    rarely have em-dashes but check)

Skip:
  - .claude/skills/*           (external skill files we don't own)
  - .claude/worktrees/*        (throwaway sandboxes)
  - **/_archive/**             (archived dashboards / docs)
  - erd/*.html                 (regenerated from .md)
  - tmp/*                      (build artifacts)
  - outputs/*                  (generated)

Replacements:
  ' — ' / ' —' / '— ' / '—'   →   ' - ' / ' -' / '- ' / '-'
  '&mdash;'                    →   '-'  (HTML entity)
"""
import re
import sys
from pathlib import Path

ROOT = Path(r"C:/Users/mbindl/Documents/GitHub/Reporting")

INCLUDE_PATTERNS = [
    "html/*.html",
    "html/*.md",
    "erd/*.md",
    "*.md",
    "CLAUDE.md",
    "data/qa_data/*.md",
    "parcel_development_history_etl/**/*.md",
]

# Paths to skip (substrings)
SKIP_SUBSTR = [
    "_archive",
    ".claude/skills",
    ".claude/worktrees",
    "/tmp/",
    "/outputs/",
]

# Order matters: spaced variants first so we don't leave stray double spaces
REPLACEMENTS = [
    (" — ",  " - "),   # spaced em-dash
    (" —",   " -"),
    ("— ",   "- "),
    ("—",    "-"),     # bare em-dash
    ("&mdash;",   "-"),     # HTML entity
]


def should_skip(p: Path) -> bool:
    s = str(p).replace("\\", "/")
    return any(skip in s for skip in SKIP_SUBSTR)


def main() -> None:
    seen: set[Path] = set()
    files: list[Path] = []
    for pat in INCLUDE_PATTERNS:
        for p in ROOT.glob(pat):
            if p.is_file() and p not in seen and not should_skip(p):
                seen.add(p); files.append(p)

    print(f"Scanning {len(files)} files...")
    total_replacements = 0
    files_touched = 0
    for p in sorted(files):
        try:
            text = p.read_text(encoding="utf-8")
        except (UnicodeDecodeError, PermissionError) as e:
            print(f"  skip {p.relative_to(ROOT)}: {e}")
            continue

        before = text
        for old, new in REPLACEMENTS:
            text = text.replace(old, new)

        if text != before:
            n = sum(before.count(old) for old, _ in REPLACEMENTS)
            print(f"  {p.relative_to(ROOT)}: {n} replacements")
            p.write_text(text, encoding="utf-8")
            files_touched += 1
            total_replacements += n

    print(f"\nDone: {files_touched} files modified, {total_replacements} em-dashes replaced.")


if __name__ == "__main__":
    main()
