"""
Central configuration for the Residential Units ETL.
All paths, field names, service URLs, and constants live here.
"""

# ── Geodatabase ───────────────────────────────────────────────────────────────
GDB        = r"C:\GIS\ParcelHistory.gdb"
SOURCE_FC  = GDB + r"\Parcel_History_Attributed"
OUTPUT_FC  = GDB + r"\Residential_Parcels_History"

# QA tables (written to GDB so they open directly in ArcGIS Pro)
QA_UNITS_BY_YEAR        = GDB + r"\QA_Units_By_Year"
QA_LOST_APNS            = GDB + r"\QA_Lost_APNs"
QA_APN_CROSSWALK        = GDB + r"\QA_APN_Crosswalk"
QA_DUPLICATE_APN_YEAR   = GDB + r"\QA_Duplicate_APN_Year"
QA_SPATIAL_COMPLETENESS = GDB + r"\QA_Spatial_Completeness"
QA_GENEALOGY_APPLIED    = GDB + r"\QA_Genealogy_Applied"

# ── Input CSV ─────────────────────────────────────────────────────────────────
CSV_PATH = (
    r"C:\Users\mbindl\Documents\GitHub\Reporting"
    r"\data\raw_data\ExistingResidential_2012_2025_unstacked.csv"
)

# ── Parcel genealogy ───────────────────────────────────────────────────────────
# Raw notes CSVs from the CSV author (free-text, parsed once by build_genealogy_master.py)
GENEALOGY_NOTES_1 = (
    r"C:\Users\mbindl\Documents\GitHub\Reporting"
    r"\data\raw_data\parcel_geneology_notes.csv"
)
GENEALOGY_NOTES_2 = (
    r"C:\Users\mbindl\Documents\GitHub\Reporting"
    r"\data\raw_data\parcel_geneology_notes_2.csv"
)
# Structured master genealogy CSV — generated by build_genealogy_master.py,
# reviewed and edited by analyst, consumed by s02b on every ETL run.
GENEALOGY_MASTER = (
    r"C:\Users\mbindl\Documents\GitHub\Reporting"
    r"\data\raw_data\apn_genealogy_master.csv"
)

# ── Feature class field names ─────────────────────────────────────────────────
FC_APN    = "APN"
FC_YEAR   = "YEAR"
FC_UNITS  = "Residential_Units"
FC_COUNTY = "COUNTY"

# Spatial attribute fields written by s05
SPATIAL_FIELDS = [
    "PARCEL_ACRES", "PARCEL_SQFT",
    "WITHIN_TRPA_BNDY", "WITHIN_BONUSUNIT_BNDY",
    "TOWN_CENTER", "LOCATION_TO_TOWNCENTER",
    "TAZ", "PLAN_ID", "PLAN_NAME",
    "ZONING_ID", "ZONING_DESCRIPTION",
    "REGIONAL_LANDUSE",
]

# ── El Dorado APN format change ───────────────────────────────────────────────
# El Dorado County (COUNTY = 'EL') added a leading zero to the APN suffix
# starting in 2018. e.g. 080-155-11 → 080-155-011.
EL_PAD_YEAR = 2018

# ── Years in scope ────────────────────────────────────────────────────────────
CSV_YEARS = list(range(2012, 2026))   # 2012 – 2025 inclusive

# ── AllParcels MapServer (geometry fetch for missing parcels) ─────────────────
ALLPARCELS_URL = "https://maps.trpa.org/server/rest/services/AllParcels/MapServer"
# Layer 3 = current (all-years combined) parcel layer — used as geometry fallback in s03
ALL_PARCELS_CURRENT = ALLPARCELS_URL + "/3"

# Layer index per year — verify against the service directory if layers shift
YEAR_LAYER = {
    2012:  8,
    2013:  7,
    2014:  6,
    2015:  5,
    2016: 18,
    2017: 17,
    2018: 20,
    2019: 22,
    2020: 24,
    2021: 26,
    2022: 28,
    2023: 30,
    2024: 32,
    2025: 34,
}

# ── Spatial join service URLs (confirmed) ─────────────────────────────────────
SPATIAL_SOURCES = {
    "TRPA_bdy"         : "https://maps.trpa.org/server/rest/services/Boundaries/FeatureServer/4",
    "BonusUnit"        : "https://maps.trpa.org/server/rest/services/Housing/MapServer/8",
    "TownCenter"       : "https://maps.trpa.org/server/rest/services/Boundaries/FeatureServer/1",
    "LocationToTownCtr": "https://maps.trpa.org/server/rest/services/Planning/FeatureServer/4",
    "TAZ"              : "https://maps.trpa.org/server/rest/services/Transportation_Planning/MapServer/6",
    "LocalPlan"        : "https://maps.trpa.org/server/rest/services/Planning/FeatureServer/2",
    "Zoning"           : "https://maps.trpa.org/server/rest/services/Zoning/MapServer/0",
    "RegionalLandUse"  : "https://maps.trpa.org/server/rest/services/LocalPlan/MapServer/7",
}

# ── Crosswalk spatial join parameters ────────────────────────────────────────
CLOSEST_MAX_METERS = 50   # max distance for CLOSEST fallback in centroid join
