"""
Central configuration for the Development History ETL.
All paths, field names, service URLs, and constants live here.
"""

# ── Geodatabase ───────────────────────────────────────────────────────────────
GDB        = r"C:\GIS\ParcelHistory.gdb"
SOURCE_FC  = GDB + r"\Parcel_History_Attributed"   # original — never edited
WORKING_FC = GDB + r"\Parcel_History_Working"       # cleaned copy — preprocess output
OUTPUT_FC  = GDB + r"\Parcel_Development_History"   # ETL output (main.py)

# QA tables (written to GDB so they open directly in ArcGIS Pro)
QA_UNITS_BY_YEAR        = GDB + r"\QA_Units_By_Year"
QA_LOST_APNS            = GDB + r"\QA_Lost_APNs"
QA_APN_CROSSWALK        = GDB + r"\QA_APN_Crosswalk"
QA_DUPLICATE_APN_YEAR   = GDB + r"\QA_Duplicate_APN_Year"
QA_SPATIAL_COMPLETENESS = GDB + r"\QA_Spatial_Completeness"
QA_GENEALOGY_APPLIED    = GDB + r"\QA_Genealogy_Applied"
QA_FC_NOT_IN_CSV        = GDB + r"\QA_FC_Units_Not_In_CSV"
QA_TOPO_DUPLICATE       = GDB + r"\QA_Topo_DuplicateAPN"
QA_TOPO_OVERLAP         = GDB + r"\QA_Topo_Overlap"
QA_TOPO_AREA_SHIFT      = GDB + r"\QA_Topo_AreaShift"
QA_SOURCE_VS_SERVICE      = GDB + r"\QA_Source_vs_Service"
QA_UNIT_RECONCILIATION    = GDB + r"\QA_Unit_Reconciliation"

# ── Input CSV ─────────────────────────────────────────────────────────────────
CSV_PATH = (
    r"C:\Users\mbindl\Documents\GitHub\Reporting"
    r"\data\raw_data\ExistingResidential_2012_2025_unstacked.csv"
)
# Tourist Accommodation Units — wide format, APN x CY2012..CY2025
TOURIST_UNITS_CSV = (
    r"C:\Users\mbindl\Documents\GitHub\Reporting"
    r"\data\raw_data\TouristUnits_2012to2025.csv"
)
# Commercial Floor Area SqFt — wide format, APN x CY<year>
COMMERCIAL_SQFT_CSV = (
    r"C:\Users\mbindl\Documents\GitHub\Reporting"
    r"\data\raw_data\CommercialFloorArea_2012to2025.csv"
)
# Service-only APNs — produced by compare_source_to_service.py
# APNs present in All Parcels service but missing from OUTPUT_FC
SERVICE_ONLY_CSV = (
    r"C:\Users\mbindl\Documents\GitHub\Reporting"
    r"\data\raw_data\apn_service_only.csv"
)

# ── Parcel genealogy ───────────────────────────────────────────────────────────
# Raw notes CSVs from the CSV author (free-text, parsed once by build_genealogy_master.py)
GENEALOGY_NOTES_1 = (
    r"C:\Users\mbindl\Documents\GitHub\Reporting"
    r"\data\raw_data\parcel_geneology_notes.csv"
)
GENEALOGY_NOTES_2 = (
    r"C:\Users\mbindl\Documents\GitHub\Reporting"
    r"\data\raw_data\parcel_geneology_notes_2.csv"
)
# Structured master genealogy CSV — generated by build_genealogy_master.py,
# reviewed and edited by analyst, consumed by s02b on every ETL run.
GENEALOGY_MASTER = (
    r"C:\Users\mbindl\Documents\GitHub\Reporting"
    r"\data\raw_data\apn_genealogy_master.csv"
)
# Spatially-derived genealogy CSV — generated by build_spatial_genealogy.py,
# consumed by s02b alongside the manual master.
GENEALOGY_SPATIAL = (
    r"C:\Users\mbindl\Documents\GitHub\Reporting"
    r"\data\raw_data\apn_genealogy_spatial.csv"
)
# Accela permit-system genealogy — generated by parse_genealogy_sources.py.
# Covers 2021–2025 splits/merges/renames from the permit database.
GENEALOGY_ACCELA = (
    r"C:\Users\mbindl\Documents\GitHub\Reporting"
    r"\data\raw_data\apn_genealogy_accela.csv"
)
# LTinfo parcel genealogy — generated by parse_genealogy_sources.py.
# change_year is blank for most rows (pre-2021); rows without change_year
# are skipped by s02b until dates are filled in.
GENEALOGY_LTINFO = (
    r"C:\Users\mbindl\Documents\GitHub\Reporting"
    r"\data\raw_data\apn_genealogy_ltinfo.csv"
)
# Consolidated master table — generated by build_genealogy_tahoe.py.
# Merges all four sources with canonical APN formatting, deduplication,
# and lost_apn validation flags. This is what s02b reads when available.
GENEALOGY_TAHOE = (
    r"C:\Users\mbindl\Documents\GitHub\Reporting"
    r"\data\raw_data\apn_genealogy_tahoe.csv"
)
# Minimum fraction of an old parcel's area that must overlap a new APN
# for the event to be recorded (0.50 = 50 %).
SPATIAL_GENEALOGY_OVERLAP_THRESHOLD = 0.50

# ── Feature class field names ─────────────────────────────────────────────────
FC_APN              = "APN"
FC_YEAR             = "YEAR"
FC_UNITS            = "Residential_Units"
FC_COUNTY           = "COUNTY"
FC_TOURIST_UNITS    = "TouristAccommodation_Units"
FC_COMMERCIAL_SQFT  = "CommercialFloorArea_SqFt"

# Spatial attribute fields written by s05
SPATIAL_FIELDS = [
    "PARCEL_ACRES", "PARCEL_SQFT",
    "WITHIN_TRPA_BNDY", "WITHIN_BONUSUNIT_BNDY",
    "TOWN_CENTER", "LOCATION_TO_TOWNCENTER",
    "TAZ", "PLAN_ID", "PLAN_NAME",
    "ZONING_ID", "ZONING_DESCRIPTION",
    "REGIONAL_LANDUSE",
]

# ── El Dorado APN format change ───────────────────────────────────────────────
# El Dorado County (COUNTY = 'EL') added a leading zero to the APN suffix
# starting in 2018. e.g. 080-155-11 → 080-155-011.
EL_PAD_YEAR = 2018

# ── Years in scope ────────────────────────────────────────────────────────────
CSV_YEARS        = list(range(2012, 2026))   # 2012 – 2025 inclusive
# Years where SOURCE_FC already has native Residential_Units values curated
# from prior team efforts.  These years support a two-source reconciliation
# between the CSV (coworker's latest effort) and the FC native values.
FC_NATIVE_YEARS  = [2012] + list(range(2018, 2026))

# ── AllParcels MapServer (geometry fetch for missing parcels) ─────────────────
ALLPARCELS_URL = "https://maps.trpa.org/server/rest/services/AllParcels/MapServer"
# Layer 3 = current (all-years combined) parcel layer — used as geometry fallback in s03
ALL_PARCELS_CURRENT = ALLPARCELS_URL + "/3"

# Layer index per year — verify against the service directory if layers shift
YEAR_LAYER = {
    2012:  8,
    2013:  7,
    2014:  6,
    2015:  5,
    2016: 18,
    2017: 17,
    2018: 20,
    2019: 22,
    2020: 27,
    2021: 29,
    2022: 30,
    2023: 31,
    2024: 32,
    # 2025 layer not yet published on AllParcels MapServer
}

# ── Jurisdictions spatial join service ────────────────────────────────────────
JURISDICTION_SVC = "https://maps.trpa.org/server/rest/services/Boundaries/FeatureServer/10"

# Maps full county names (as returned by the service) to 2-char codes
COUNTY_CODE_MAP = {
    "Washoe"                 : "WA",
    "El Dorado"              : "EL",
    "Placer"                 : "PL",
    "Douglas"                : "DG",
    "Carson City"            : "CC",
    "City of South Lake Tahoe": "CSLT",
}

# ── Spatial join service URLs (confirmed) ─────────────────────────────────────
SPATIAL_SOURCES = {
    "TRPA_bdy"         : "https://maps.trpa.org/server/rest/services/Boundaries/FeatureServer/4",
    "BonusUnit"        : "https://maps.trpa.org/server/rest/services/Housing/MapServer/8",
    "TownCenter"       : "https://maps.trpa.org/server/rest/services/Boundaries/FeatureServer/1",
    "LocationToTownCtr": "https://maps.trpa.org/server/rest/services/Planning/FeatureServer/4",
    "TAZ"              : "https://maps.trpa.org/server/rest/services/Transportation_Planning/MapServer/6",
    "LocalPlan"        : "https://maps.trpa.org/server/rest/services/Planning/FeatureServer/2",
    "Zoning"           : "https://maps.trpa.org/server/rest/services/Zoning/MapServer/0",
    "RegionalLandUse"  : "https://maps.trpa.org/server/rest/services/LocalPlan/MapServer/7",
}

# ── Crosswalk spatial join parameters ────────────────────────────────────────
CLOSEST_MAX_METERS = 50   # max distance for CLOSEST fallback in centroid join
