"""
Step 2b — Apply parcel genealogy corrections to df_csv.

Loads apn_genealogy_master.csv (generated by build_genealogy_master.py and
reviewed by the analyst) and applies APN substitutions to df_csv before
csv_lookup is built.

For each genealogy record where change_year is populated:
  - Rows in df_csv where APN == old_apn AND Year >= change_year are updated
    so that APN becomes new_apn.
  - Only primary rows (is_primary == 1) are applied — secondary split
    successors are listed in the master CSV for reference only.
  - Substitution is skipped if (new_apn, year) already exists in df_csv to
    avoid inflating unit counts.

This step runs AFTER the El Dorado APN fix and BEFORE csv_lookup is built,
so the lookup already references the correct current APN for each year when
the FC join happens.  The spatial crosswalk in s03 then handles any remaining
unresolved cases.

Writes QA_Genealogy_Applied to GDB.
"""
import sys
sys.path.insert(0, str(__import__('pathlib').Path(__file__).parents[1]))

import pandas as pd

from config import GENEALOGY_MASTER, QA_GENEALOGY_APPLIED
from utils  import get_logger, df_to_gdb_table

log = get_logger("s02b_genealogy")


def _load_master() -> pd.DataFrame:
    """
    Load apn_genealogy_master.csv.
    Returns only primary, apply-ready rows (is_primary=1, change_year populated).
    """
    try:
        df = pd.read_csv(GENEALOGY_MASTER, dtype=str)
    except FileNotFoundError:
        log.warning(
            "apn_genealogy_master.csv not found at %s. "
            "Run build_genealogy_master.py first.  Skipping genealogy step.",
            GENEALOGY_MASTER,
        )
        return pd.DataFrame()

    df.columns = df.columns.str.strip()
    required = {"old_apn", "new_apn", "change_year", "is_primary"}
    missing  = required - set(df.columns)
    if missing:
        log.error("Master CSV missing columns: %s  Skipping.", missing)
        return pd.DataFrame()

    df["old_apn"]    = df["old_apn"].str.strip()
    df["new_apn"]    = df["new_apn"].str.strip()
    df["is_primary"] = pd.to_numeric(df["is_primary"], errors="coerce").fillna(0).astype(int)

    # Only apply primary successors with a known change year
    df = df[df["is_primary"] == 1].copy()
    df["change_year"] = pd.to_numeric(df["change_year"], errors="coerce")
    df = df.dropna(subset=["change_year"])
    df["change_year"] = df["change_year"].astype(int)

    log.info("Master CSV: %d apply-ready rows (is_primary=1, change_year set)",
             len(df))

    no_year = pd.read_csv(GENEALOGY_MASTER, dtype=str)
    no_year = no_year[no_year["is_primary"].astype(str).str.strip() == "1"]
    no_year_ct = no_year["change_year"].isna().sum() + (no_year["change_year"] == "").sum()
    if no_year_ct:
        log.warning(
            "  %d primary rows have no change_year (PARCEL_NEW or unresolved) "
            "— skipped. Fill in change_year manually in the master CSV to include them.",
            no_year_ct,
        )

    return df


def run(df_csv: pd.DataFrame) -> pd.DataFrame:
    log.info("=== Step 2b: Apply genealogy APN corrections ===")

    master = _load_master()
    if master.empty:
        log.info("No genealogy corrections to apply.")
        return df_csv

    # Build set of existing (APN, Year) combos to detect conflicts
    existing = set(zip(df_csv["APN"], df_csv["Year"]))

    df = df_csv.copy()
    qa_rows = []

    for _, rec in master.iterrows():
        old_apn     = rec["old_apn"]
        new_apn     = rec["new_apn"]
        change_year = int(rec["change_year"])
        change_type = str(rec.get("change_type", "")).strip()

        if old_apn == new_apn:
            continue  # no-op

        # Rows in df_csv where old_apn needs to be replaced
        mask = (df["APN"] == old_apn) & (df["Year"] >= change_year)
        if not mask.any():
            continue

        year_rows   = df.loc[mask, "Year"]
        years_all   = year_rows.tolist()

        # Skip years where new_apn already has data (avoid double-counting)
        conflict_years = [y for y in years_all if (new_apn, y) in existing]
        safe_years     = [y for y in years_all if (new_apn, y) not in existing]

        if conflict_years:
            log.debug(
                "  Conflict skip: %s → %s already in df for years %s",
                old_apn, new_apn, conflict_years,
            )

        if safe_years:
            safe_mask = mask & df["Year"].isin(safe_years)
            units_moved = int(df.loc[safe_mask, "Units_CSV"].sum())
            df.loc[safe_mask, "APN"] = new_apn

            # Update existing set
            for y in safe_years:
                existing.add((new_apn, y))
                existing.discard((old_apn, y))

            qa_rows.append({
                "Old_APN"         : old_apn,
                "New_APN"         : new_apn,
                "Change_Year"     : change_year,
                "Change_Type"     : change_type,
                "Years_Updated"   : len(safe_years),
                "Years_Conflicted": len(conflict_years),
                "Total_Units_Moved": units_moved,
            })

    log.info("Genealogy corrections applied: %d APN substitutions", len(qa_rows))
    if qa_rows:
        total_units = sum(r["Total_Units_Moved"] for r in qa_rows)
        log.info("  Total unit-years remapped: %d", total_units)

    # ── Write QA table ────────────────────────────────────────────────────────
    if qa_rows:
        df_qa = pd.DataFrame(qa_rows)
        try:
            df_to_gdb_table(
                df_qa, QA_GENEALOGY_APPLIED,
                text_lengths={"Old_APN": 50, "New_APN": 50, "Change_Type": 30},
            )
            log.info("Written → %s", QA_GENEALOGY_APPLIED)
        except Exception as exc:
            log.warning("Could not write QA_Genealogy_Applied: %s", exc)

    log.info("Step 2b complete.")
    return df


if __name__ == "__main__":
    import s02_load_csv as s02
    df_csv, _ = s02.run()
    df_fixed  = run(df_csv)
    changed   = (df_fixed["APN"] != df_csv["APN"]).sum()
    print(f"Rows with APN changed: {changed:,}")
